#### 01_QC

# FastP automatically compresses data when the output has a ".gz" extension.
# How much do you want to compress? Range from 1 (least compressed) to 9 (most compressed).
# Type: Integer
# Default = 6
qc_compression: 6
