###############################################
##                                           ##
##         Host Cell RNAseq Pipeline         ##
##      Step 1: FastP - Quality Control      ##
##              AJB - Jan 2025               ##
##                                           ##
###############################################

from snakemake.utils import min_version
min_version("3.2")

# Define groups based on input data. 
# This is extracting just the group name (i.e. "CP-1") from the available files.
GROUPS, = glob_wildcards("00_Raw/{group}.1.fastq.gz")

# Declare final rule that will determine completion of script based on created files.
rule all: 
   input: expand("01_QC/qc/{group}_qc.1.fastq.gz", group=GROUPS)

# FastP - Quality Control, Trimming, of RNAseq Reads
rule fastp:
    input: 
        reads1i="00_Raw/{group}.1.fastq.gz",
        reads2i="00_Raw/{group}.2.fastq.gz"
    output: 
        reads1o="01_QC/qc/{group}_qc.1.fastq.gz",
        reads2o="01_QC/qc/{group}_qc.2.fastq.gz"
    conda: "envs/fastp.yml"
    params:
        sample_name = "01_QC/qc_data/{group}.html",
        compression = 6
    threads: 4
    shell: "fastp -i {input.reads1i} -o {output.reads1o} -I {input.reads2i} -O {output.reads2o} -w {threads} --detect_adapter_for_pe -z {params.compression} -h {params.sample_name} --json /dev/null"