###############################################
##                                           ##
##         Host Cell RNAseq Pipeline         ##
##      Step 1: FastP - Quality Control      ##
##              AJB - Jan 2025               ##
##                                           ##
###############################################

from snakemake.utils import min_version
min_version("3.2")

# Declare config file.
configfile: "config/config.yaml"
compression_val = config["qc_compression"]

# Define groups based on input data. 
# This is extracting just the group name (i.e. "CP-1") from the available files.
GROUPS, = glob_wildcards("00_Raw/{group}.1.fastq.gz")

# Declare final rule that will determine completion of script based on created files.
rule all: 
   input: expand("01_QC/qc/{group}_qc.1.fastq.gz", group=GROUPS)

# FastP - Quality Control, Trimming, of RNAseq Reads
rule fastp:
    input: 
        reads1i="00_Raw/{group}.1.fastq.gz",
        reads2i="00_Raw/{group}.2.fastq.gz"
    output: 
        reads1o="01_QC/qc/{group}_qc.1.fastq.gz",
        reads2o="01_QC/qc/{group}_qc.2.fastq.gz"
    conda: "envs/fastp.yml"
    params:
        sample_html = "01_QC/qc_data/{group}.html",
        sample_name = "{group}",
        compression = compression_val
    threads: 4
    shell: "fastp --in1 {input.reads1i} --out1 {output.reads1o} --in2 {input.reads2i} --out2 {output.reads2o} -w {threads} --detect_adapter_for_pe --correction --trim_poly_x --compression {params.compression} --html {params.sample_html} --json /dev/null --report_title {params.sample_name}"