
# Where is your .fasta file with your adapter sequence(s)?
# Type: String
# Default = ""
path_to_adapter: "data/adapter.fasta"

# Where is your index folder for STAR?
# Type: String
# Default = ""
path_to_index: "data/index"

# If you need to rename files (i.e. from SRA), you need to make a file
#   with the initial fastq names in the first column and the new names
#   in the second column. Save as .tsv or .txt - must be tab-delimited!
# 
# List the path to the .txt file?
# Type: String
# Default = ""
path_to_reference: "data/seq_reference.txt"
